# -*- coding: utf-8 -*-
"""ANA_Extração.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8OUKooQnmx62eDsh4Bnsw8qFJQGC5lF

# Se conectando com o Google Drive
"""

from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd '/gdrive/My Drive/PDFs_ANA'
# %ls

"""# Separando os arquivos texto que serão considerados"""

import pandas as pd

Base_dados = pd.read_csv("Potaria_ana.txt", encoding='latin-1', sep = '	')

portarias_link = Base_dados[Base_dados['Freq'] > 10]
portarias_link = portarias_link[portarias_link['Freq'] < 56]

"""# Entrando com os pacotes necessários"""

!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install pdf2image
!apt-get install -y poppler-utils
from pdf2image import convert_from_path
from PIL import Image

pip install easyocr

pip install openpyxl==3.0.5

pip uninstall opencv-python

pip install opencv-python==3.4.5.20

import easyocr

"""# Realizando os downloads dos PDF's"""

from selenium import webdriver
from pdf2image import convert_from_path
from IPython.display import Image

import easyocr
import os

import time

# initialise browser
#browser = webdriver.Chrome(os.getcwd()+'/chromedriver')

# Entrando com o banco de dados

url_list = list(portarias_link['Link'])
            
texto_final = []
Url_error = []

for i in range(0,len(url_list)):

# 0:10
# 10:20

  try:

    try:

      import sys
      sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
      from selenium import webdriver
      chrome_options = webdriver.ChromeOptions()
      chrome_options.add_argument('--headless')
      chrome_options.add_argument('--no-sandbox')
      chrome_options.add_argument('--disable-dev-shm-usage')
      browser = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

      browser.get(str(url_list[i]).replace('[','').replace(']','').replace("'",""))

      # Fazendo Download dos arquivos em PDF

      download = browser.find_element_by_xpath('//*[@id="download"]')

      download.click()

    except:
      print(url_list[i])
      Url_error.append(url_list[i])

    time.sleep(20)

    # Transformando as páginas em jpg

    # Pegando uma lista de todos os documentos presentes na pasta

    arquivos = !ls '/gdrive/My Drive/PDFs_ANA'

    # Arrumando a lista 

    lista_arquivo = []
    for i in range(0,len(arquivos)):
      result = arquivos[i].replace('[','').replace(']','').replace("'","").replace(',','').replace('\t','').split('  ')
      lista_arquivo.append(result)
 
    lista_arquivo =[item for sublist in lista_arquivo for item in sublist]

    pdf_list = [x for x in lista_arquivo if x.endswith(('pdf'))]

    i = 0

    for pdf in pdf_list:

      pages = convert_from_path(pdf, 500)

      for page in pages[0:10]:
        i = i+1
        page.save('out'+str(i)+'.jpg', 'JPEG')

    time.sleep(20)


    # Pegando uma lista de todos os documentos presentes na pasta

    arquivos = !ls '/gdrive/My Drive/PDFs_ANA'
    lista = str(arquivos).replace('\\t',' ').split(' ')

    # Arrumando a lista 

    lista_arquivo = []
    for i in range(0,len(lista)):
      result = lista[i].replace('[','').replace(']','').replace("'","").replace(',','')
      lista_arquivo.append(result)

    # Pegando apenas os arquivos de jpg

    imagens_lista = [x for x in lista_arquivo if x.endswith(('jpg', 'png'))]
    imagens_lista.sort()
  
    # Separando o conteudo textual presente nas imagens

    temporario = []
    texto = []
    for i in range(0,len(imagens_lista)):

      reader = easyocr.Reader(['pt'])
      resultado = reader.readtext(imagens_lista[i])

      # Formatando a parte textual 

      texto_parte = []
      for i in range(0,len(resultado)):
        result = str(resultado[i]).split("'")[1].split("'")[0]
        texto_parte.append(result)

        texto = []
        texto.append(" ".join(str(x) for x in texto_parte))

      print(texto)

      temporario.append([''.join(texto[:len(texto)])])

      flat_list = [item for sublist in temporario for item in sublist]

    texto_final.append(temporario)

    # Removendo o conteudo presente no Drive

    !rm ./*pdf
    !rm ./*jpg
    !rm ./*crdownload

    time.sleep(20)

  except:
    print(url_list[i])
    texto_final.append(' ')

    !rm ./*pdf
    !rm ./*jpg
    !rm ./*crdownload

    time.sleep(20)

"""# Estruturando o Dataframe"""

# Criando um DataFrame para alocar os outputs

BANCO = pd.DataFrame (portarias_link['ID'] ,columns=['ID'])
BANCO['Texto_lei'] = texto_final
BANCO['Data_lei'] = ['']*len(texto_final)
BANCO['Data_publicação'] = portarias_link['Data_publicação']
BANCO['Tipo_lei'] = portarias_link['Tipo_lei']
BANCO['Revogada'] = portarias_link['Revogada']
BANCO['Setor'] = portarias_link['Setor']

BANCO

# Exportando em formato TXT

BANCO.to_csv("Portaria_ANA_maiores_10_parte1.txt", index=False, encoding='utf-8-sig', sep = '汉')